### ISSUE TITLE
level 9 skywalking

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#112]
1.0029 in this room in level 9 when you jump towards the gate you can stand in the air on an invisible tile.

![poa-skywalker](https://user-images.githubusercontent.com/4971163/224488254-a1db937f-51bf-4bc3-8e09-6c3683a0c25d.gif)

**Comment by MrBlinky** [comment]
So this is not just a case of invisible tiles?

**Comment by filmote** [comment]
No unfortunately.  In the section where I determine if you can do a running jump I then work out which jump you can do - long, medium or short and on the same level / dropping a level - I had some incorrect logic.  I really need to play test this some more.

**Comment by ace-dent** [comment]
May be related...
Tested v1.00, sim, Level 1:
![ArduboyRecording](https://user-images.githubusercontent.com/473224/224885367-d3c7c1e3-a09f-4431-b30c-55e2fe7e5bf9.gif)

**Comment by ace-dent** [comment]
Also 'feels' harder to make this L1 jump (I've done 100 times)... not sure if anything changed- or just me!
![ArduboyRecording (1)](https://user-images.githubusercontent.com/473224/224885734-b248c930-8496-4e53-bfd1-2941fc6a5889.gif)

**Comment by filmote** [comment]
Are you testing with the 1.01.beta.001 version?

**Comment by ace-dent** [comment]
Re-tested issues with Version 1.01 Beta 001, Emulator.
1. L1 issue of air walking remains.
2. Jumping seems fine. (may be I got use to physical HW and the emu is laggy on my laptop). Would appreciate someone else playing through L1.

**Comment by filmote** [comment]
OK .. I will not be able to test tonight.  But will test again.

The change I did really should only affect a jump that drops a level not the two you highlighted .. but stranger things have happened!

**Comment by filmote** [comment]
Have merged into main.  Will package up soon.

**Comment by MrBlinky** [comment]
Version 1.1 Beta 002 tested skywalking as in the original 1st post and it is solved.

**Comment by ace-dent** [comment]
Re-tested L1, v1.01 Beta 004, Sim.
-- Issue still kinda remains... but now I'm trying to cause a problem. Probably ok for most users?

![jump](https://user-images.githubusercontent.com/473224/226690786-555654ed-175d-4386-ac39-2641d7464f04.gif)

**Comment by filmote** [comment]
Updated in Beta 005

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, Sim.
-- L1: Still can air walk jumps going left -> right.

![Airwalk](https://user-images.githubusercontent.com/473224/229197795-bdc41ee2-1cd9-4da0-9a78-ae8bbaf2ac1b.gif)

**Comment by filmote** [comment]
A bit of a fudge fix .. but you cannot jump from that position anymore when the tiles are arranged like this [floor] [floor] [gap] [gap] [floor]. when running left to right or the reverse when running right to left.  If detected, it will force the prince to take another step before jumping - solves the problem with the available memory left but introduces a lag between pressing the button and actually jumping.

Fixed in Version 1.01 Beta 013.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 013, Sim.
- This 'fix' doesn't feel great when playing. Just feels like we are not registering key presses.
-  It would be better to allow the jump (as before), but correctly detect the landing is on air not a platform- so the prince falls.
- Also, not fixed elsewhere in L1 (see recording).

![AirwalkL1](https://user-images.githubusercontent.com/473224/229319924-3cf0e461-04be-4fe5-bc03-99e94c66c491.gif)

**Comment by filmote** [comment]
I played the DOS version and this extra step is exactly what that version does.  I have just realised what mechner did there!  I have been trying to accommodate for jumps at various points in the tiles (in my version 2, 6, 10) with jumps that cater for the various distances.  He just made you continue for a step or half a step so he can cut down on all the jump types.

**Comment by filmote** [comment]
I was concerned the player would think that he could clear the jump.

How about this?


![Image](https://user-images.githubusercontent.com/17228490/229329692-095fa12d-70ba-4b70-a22d-d1286acf1160.gif)

![Image](https://user-images.githubusercontent.com/17228490/229329693-20b0ec2b-196e-4165-bbef-a853edbbe4c3.gif)

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 015, Sim.
- L1: May be we went too far!? See video.
- This jump we should have made/ grabbed the edge, but instead we fall like a stone...

![SlipperyJump](https://user-images.githubusercontent.com/473224/229346440-0b019252-f03f-49e8-87bf-0d02a94f7a3b.gif)

**Comment by filmote** [comment]
Its the same video really as my second one.

The problem is that if we make this one a valid jump, it says you really cannot miss this jump from any position.  The only way you could fall is to run over it.  If you are going to jump that far out from a gap, maybe you should die?

Its too narrow to have the play grab on as well.

I wonder what the original does?
